name         'gsick-grafana'
version      '0.0.1'
source       'https://github.com/gsick/puppet-grafana.git'
author       'Gamaliel Sick'
license      'MIT'
summary      'Grafana Puppet installation module'
description  'Puppet module for installing and configuring Grafana'
project_page 'https://github.com/gsick/puppet-grafana'

dependency   'puppetlabs/stdlib', '>= 4.2.2'
